# Project information
site_name: pyjanitor documentation
site_url: https://pyjanitor-devs.github.io/pyjanitor
site_description: >-
  Python implementation of the R package janitor

# Repository
repo_name: "pyjanitor-devs/pyjanitor"
repo_url: "https://github.com/pyjanitor-devs/pyjanitor"

# Configuration
docs_dir: mkdocs/
watch:
  - janitor/

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "blue grey"
      accent: "light blue"
  icon:
    logo: "fontawesome/solid/book"
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.top
    - toc.follow
    - content.code.copy
  language: en

# Page tree
# We customize the navigation by hand to control the order
# in which pages show up.
nav:
  - Home: index.md
  - API Reference:
      - Functions: api/functions.md
      - Biology: api/biology.md
      - Chemistry: api/chemistry.md
      - Engineering: api/engineering.md
      - Finance: api/finance.md
      - Input/Output (io): api/io.md
      - Machine Learning: api/ml.md
      - Math: api/math.md
      # - PySpark: api/pyspark.md  # will be added back later
      - Timeseries: api/timeseries.md
      - XArray: api/xarray.md
  - Development Guide: devguide.md
  - Changelog: CHANGELOG.md
  - Authors: AUTHORS.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "google"
            docstring_options:
              trim_doctest_flags: true
            show_root_toc_entry: false
            show_submodules: true
            show_source: true
# - mknotebooks:
#     execute: true
#     write_markdown: true
#     allow_errors: true
#     timeout: 1200
#     binder: true
#     binder_service_name: "gh"
#     binder_branch: "master"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/apidocs.css
