# Unconditionally release pyjanitor.
# If no version bump has happened, then nothing happens.
# If a version bump has happened, then the build will automatically deploy
# a release to PyPI.

steps:
  - script: |
      $(activate.command) pyjanitor-dev
      conda install twine setuptools
    displayName: 'Install Twine and setuptools'
  - script: |
      $(activate.command) pyjanitor-dev
      python setup.py sdist bdist_wheel
    displayName: 'Build artifacts to deploy.'
  - script: |
      $(activate.command) pyjanitor-dev
      twine upload dist/* --skip-existing --username $(pypi.username) --password $(pypi.password)
    displayName: 'Upload built artifacts.'
