name: Auto-release

on:
  # The below workflow_dispatch section is for a "manual" kick off of the
  # auto-release script. To cut a new release, navigate to the Actions section
  # of the repo and select this workflow (Auto-release) on the right hand side.
  # Then, click "Run workflow" and you will be prompted to input the new
  # version (which should be major, minor, or patch).
  workflow_dispatch:
    inputs:
      version_name:
        description: "One of major, minor, or patch"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  id-token: write

env:
  DEFAULT_VERSION_NAME: patch

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Pull latest commits of dev branch
        run: |
          git checkout dev
          git pull

      - name: Setup Python environment
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: latest
          cache: true
          cache-write: true

      - name: Set up Python tools
        run: uv tool install bump2version

      - name: Set version name
        run: echo "VERSION_NAME=${{ github.event.inputs.version_name || env.DEFAULT_VERSION_NAME }}" >> $GITHUB_ENV

      - name: Dry run bump2version
        run: bump2version --dry-run ${{ env.VERSION_NAME }} --allow-dirty --verbose

      - name: Store new version number
        run: echo "version_number=$(bump2version --dry-run --list ${{ env.VERSION_NAME }} | grep new_version | sed -r 's/^.*=//')" >> $GITHUB_ENV

      - name: Display new version number
        run: |
          echo "version_name: ${{ env.VERSION_NAME }}"
          echo "version_number: v${{ env.version_number }}"

      - name: Ensure repo status is clean
        run: git status

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Run bump2version
        run: bump2version ${{ env.VERSION_NAME }} --verbose

      - name: Ensure tag creation
        run: git tag | grep ${{ env.version_number }}

      - name: Install llamabot package
        run: pixi run pip install llamabot[cli]

      - name: Write release notes
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          llamabot configure default-model --model-name="${{ secrets.DEFAULT_LANGUAGE_MODEL }}"
          llamabot git write-release-notes

      - name: Commit release notes
        run: |
          pixi run pre-commit run --all-files || pixi run pre-commit run --all-files
          git add .
          git commit -m "Add release notes for ${{ env.version_number }}"

      - name: Build package
        run: pixi run release

      - name: Publish package (trusted publishing)
        run: uv publish --trusted-publishing always

      - name: Push changes with tags
        run: |
          git push && git push --tags

      - name: Create release in GitHub repo
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "docs/releases/v${{ env.version_number }}.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version_number }}

      - name: Ensure complete
        run: echo "Auto-release complete!"
