name: Build documentation

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build documentation

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
          environments: docs

      - name: Build docs
        run: pixi run build-docs

      - name: Deploy website
        if: github.ref_name == 'dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
          personal_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev'
        uses: rossjrw/pr-preview-action@v1.8.1
        with:
          source-dir: ./site
          preview-branch: gh-pages
