name: pyjanitor tests

on: [pull_request]

jobs:
  build-environment:
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - name: Setup anaconda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      # Build cache of environment
      - name: Cache conda environment
        id: cache-environment
        uses: actions/cache@v2
        # Conda environment build step depends on two files,
        # so we ensure that the hash key contains both their hashes.
        with:
          path: |
            pyjanitor-dev.tar.gz
          key: ${{ runner.os }}-env.${{ hashFiles('environment-dev.yml') }}

      - name: Build environment
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          conda env create -f environment-dev.yml
          python -m pip install .

      - name: Install conda-pack
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: conda install -c conda-forge conda-pack

      - name: Run conda-pack
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: conda pack -n pyjanitor-dev -o pyjanitor-dev.tar.gz

      # See: https://github.com/actions/upload-artifact
      - name: Upload environment
        uses: actions/upload-artifact@v2
        with:
          name: pyjanitor-dev-tarball
          path: pyjanitor-dev.tar.gz

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/download-artifact
      - name: Download environment tarball
        uses: actions/download-artifact@v2
        with:
          name: pyjanitor-dev-tarball

      - name: Unpack environment and activate it
        run: bash scripts/ci/unpack_environment.sh

      - name: Run tests
        run: |
          source /tmp/pyjanitor-dev_env/bin/activate
          python -m pip install -e .
          pytest

      - name: Inspect coverage
        run: |
          cat coverage.xml

      - name: Upload code coverage
        run: |
          source /tmp/pyjanitor-dev_env/bin/activate
          bash <(curl -s https://codecov.io/bash)

  jupyter-notebook:
    name: Execute all Jupyter notebooks
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/download-artifact
      - name: Download environment tarball
        uses: actions/download-artifact@v2
        with:
          name: pyjanitor-dev-tarball

      - name: Unpack environment and activate it
        run: bash scripts/ci/unpack_environment.sh

      - name: Execute Jupyter notebooks
        run: |
          source /tmp/pyjanitor-dev_env/bin/activate
          python -m pip install -e .
          python -m ipykernel install --user --name pyjanitor-dev
          jupyter nbconvert --to notebook --config nbconvert_config.py --execute --template full

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/download-artifact
      - name: Download environment tarball
        uses: actions/download-artifact@v2
        with:
          name: pyjanitor-dev-tarball

      - name: Unpack environment and activate it
        run: bash scripts/ci/unpack_environment.sh


      - name: Build docs
        run: |
          source /tmp/pyjanitor-dev_env/bin/activate
          python -m pip install -e .
          cd docs && make html

      - name: Netlify PR preview
        uses: netlify/actions/cli@master
        with:
          args: deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=docs/_build/html/
