name: pyjanitor tests

on:
  # only run tests and coverage when src-code changes
  push:
    branches:
      - dev
    paths:
      - "janitor/**"
      - "tests/**"
      - "pyproject.toml"
      - "pixi.lock"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - dev
    paths:
      - "janitor/**"
      - "tests/**"
      - "pyproject.toml"
      - "pixi.lock"
      - ".github/workflows/tests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        environment: [py311, py312, py313]
    runs-on: ubuntu-latest
    name: Run pyjanitor test suite (Python ${{ matrix.environment }})

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: true
          environments: ${{ matrix.environment }}

      - name: Run docstrings tests
        run: pixi run -e ${{ matrix.environment }} pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml --doctest-modules --ignore=tests janitor

      - name: Run unit tests
        run: pixi run -e ${{ matrix.environment }} pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml tests

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
