name: pyjanitor tests

on:
  # only run tests and coverage when src-code changes
  push:
    branches:
      - dev
    paths: &test-watch
      - "janitor/**"
      - "tests/**"
      - ".codecov.yml"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - dev
    paths: *test-watch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        test-subset: ["turtle", "not turtle"]
    runs-on: ubuntu-latest
    name: Run pyjanitor test suite

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          environment-file: environment-dev.yml
          use-mamba: true

      - name: Install pyjanitor
        run: python -m pip install -e .

      - name: Run docstrings tests
        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml --doctest-only janitor

      - name: Run unit tests
        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml tests -m "${{ matrix.test-subset }}"

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
