name: tests

on:
  # only run tests and coverage when src-code changes
  push:
    branches:
      - dev
    paths:
      - "janitor/**"
      - "tests/**"
      - ".codecov.yml"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - dev
    paths:
      - "janitor/**"
      - "tests/**"
      - ".codecov.yml"
      - ".github/workflows/tests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dev: [false]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        env: [ci/envs/latest.yaml]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          environment-file: ${{ matrix.env }}
          use-mamba: true

      - name: Install pyjanitor
        run: python -m pip install -e .

      - name: Run docstrings tests
        if: ${{ contains(matrix.env, 'latest.yaml') && contains(matrix.os, 'ubuntu') }}
        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml --doctest-only janitor

      - name: Run not turtle unit tests
        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml tests -m "not turtle"

      - name: Run turtle unit tests
        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml tests -m "turtle"

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
