name: pyjanitor tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        test-subset: ["turtle", "not turtle"]
    runs-on: ubuntu-latest
    name: Run pyjanitor test suite

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: pyjanitor-dev
          environment-file: environment-dev.yml
          use-mamba: true

      - name: Run unit tests
        run: |
          conda activate pyjanitor-dev
          python -m pip install -e .
          pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml --doctest-modules --doctest-glob="janitor/*.py" --ignore-glob="nbconvert_config.py" tests -m "${{ matrix.test-subset }}"

      # https://github.com/codecov/codecov-action
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          # fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
