name: pyjanitor-doc
channels:
  - conda-forge
dependencies:
  - python
  # required
  - pandas
  - pandas-flavor
  - multipledispatch
  - scipy
  # optional
  - biopython
  - natsort
  - pyspark>=3.2.0
  - rdkit
  - tqdm
  - unyt
  - xarray
  - numba
  # doc
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python
